### ISSUE TITLE
Weather module KeyError

### ISSUE THREAD

**Issue by yochananmarqos** [fredcox/gonha#4]
I've installed all the required dependencies for v1.3.0 as far as I can tell. Not sure what's causing this.

@ragouel

```
Traceback (most recent call last):
  File "/usr/sbin/gonha", line 3, in <module>
    from gonha.mainwindow import MainWindow
  File "/usr/lib/python3.8/site-packages/gonha/mainwindow.py", line 4, in <module>
    from gonha.threads import *
  File "/usr/lib/python3.8/site-packages/gonha/threads.py", line 2, in <module>
    from gonha.util import Config
  File "/usr/lib/python3.8/site-packages/gonha/util.py", line 266, in <module>
    class Weather:
  File "/usr/lib/python3.8/site-packages/gonha/util.py", line 268, in Weather
    city = config.getConfig('location')['city']
  File "/usr/lib/python3.8/site-packages/gonha/util.py", line 209, in getConfig
    return json_object[key]
KeyError: 'location'
```

**Comment by fredcox** [comment]
> I've installed all the required dependencies for v1.3.0 as far as I can tell. Not sure what's causing this.
> 
> @ragouel
> 
> ```
> Traceback (most recent call last):
>   File "/usr/sbin/gonha", line 3, in <module>
>     from gonha.mainwindow import MainWindow
>   File "/usr/lib/python3.8/site-packages/gonha/mainwindow.py", line 4, in <module>
>     from gonha.threads import *
>   File "/usr/lib/python3.8/site-packages/gonha/threads.py", line 2, in <module>
>     from gonha.util import Config
>   File "/usr/lib/python3.8/site-packages/gonha/util.py", line 266, in <module>
>     class Weather:
>   File "/usr/lib/python3.8/site-packages/gonha/util.py", line 268, in Weather
>     city = config.getConfig('location')['city']
>   File "/usr/lib/python3.8/site-packages/gonha/util.py", line 209, in getConfig
 

>     return json_object[key]
> KeyError: 'location'
> ```

Please, run gonna --config 

And try again.

If get error, put the code here.

**Comment by yochananmarqos** [comment]
Argh, I feel dumb now. I deleted the config file, ran the wizard and now it's working.

**Comment by fredcox** [comment]
Ahahaha. No problem man. It is happen.

**Comment by ragouel** [comment]
I'm getting a similar error, not sure what's causing it. I tried both with pip and without. 

<pre><code>::  Gonha 1.3.0  ::
Starting...

Error!  [  'main' Error!   ]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/gonha/mainwindow.py", line 877, in receiveThreadWeatherFinish
    self.dtwWidgets['cloudicon'].setPixmap(message['icon'])
KeyError: 'icon'
[1]    1907172 abort (core dumped)  gonha</code></pre>
