### ISSUE TITLE
Wizard does not complete

### ISSUE THREAD

**Issue by yochananmarqos** [fredcox/gonha#9]
I removed the config, chose Fahrenheit and selected my (only) M.2 NVMe.

```
2020-08-02 19:32:32 inspirognome gonha.util[1446670] INFO Starting Wizard...
? Do you want see temperatures in Kelvin, Fahrenheit or Celsius?  Fahrenheit
? Hummm, You have M.2 NVMe´s, please choose the correct device do you want monitoring:  [
Traceback (most recent call last):
  File "/usr/sbin/gonha", line 3, in <module>
    from gonha.mainwindow import MainWindow
  File "/usr/lib/python3.8/site-packages/gonha/mainwindow.py", line 4, in <module>
    from gonha.threads import *
  File "/usr/lib/python3.8/site-packages/gonha/threads.py", line 2, in <module>
    from gonha.util import Config
  File "/usr/lib/python3.8/site-packages/gonha/util.py", line 468, in <module>
    class Weather:
  File "/usr/lib/python3.8/site-packages/gonha/util.py", line 469, in Weather
    config = Config()
  File "/usr/lib/python3.8/site-packages/gonha/util.py", line 115, in __init__
    self.wizard()
  File "/usr/lib/python3.8/site-packages/gonha/util.py", line 197, in wizard
    if self.nvidia.nvidiaEntity['count'] > 0:
KeyError: 'count'
```

**Comment by fredcox** [comment]
> I removed the config, chose Fahrenheit and selected my (only) M.2 NVMe.
> 
> ```
> 2020-08-02 19:32:32 inspirognome gonha.util[1446670] INFO Starting Wizard...
> ? Do you want see temperatures in Kelvin, Fahrenheit or Celsius?  Fahrenheit
> ? Hummm, You have M.2 NVMe´s, please choose the correct device do you want monitoring:  [
> Traceback (most recent call last):
>   File "/usr/sbin/gonha", line 3, in <module>
>     from gonha.mainwindow import MainWindow
>   File "/usr/lib/python3.8/site-packages/gonha/mainwindow.py", line 4, in <module>
>     from gonha.threads import *
>   File "/usr/lib/python3.8/site-packages/gonha/threads.py", line 2, in <module>
>     from gonha.util import Config
>   File "/usr/lib/python3.8/site-packages/gonha/util.py", line 468, in <module>
>     class Weather:
>   File "/usr/lib/python3.8/site-packages/gonha/util.py", line 469, in Weather
>     config = Config()
>   File "/usr/lib/python3.8/site-packages/gonha/util.py", line 115, in __init__
>     self.wizard()
>   File "/usr/lib/python3.8/site-packages/gonha/util.py", line 197, in wizard
>     if self.nvidia.nvidiaEntity['count'] > 0:
> KeyError: 'count'
> ```

Hi, it was one bug but i was fix in release 1.6.30. I am sorry. 

best regards
